routes/web.php
<?php

Auth::routes();


Route::get('test', function () {
    // $games = \App\Game::with('tasks')->get();

    // foreach ($games as $game) {
    //     if ($game->starts_at->toDateString() <= today()->toDateString()) {
    //         $lastGamesDay = \App\Task::whereGameId($game->id)->max('day');

    //         if ($game->active_day < $lastGamesDay) {
    //             $game->active_day += 1;
    //             $game->save();

    //             foreach ($game->tasks as $task) {
    //                 if ($game->active_day === $task->day) {
    //                     $task->hidden = false;
    //                     $task->save();
    //                 }
    //             }
    //         }
    //     }
    // }

    dd(true);
});

Route::middleware(['auth'])->group(function () {
    // Logout web user
    Route::get('logout', function () {
        auth('web')->logout();
        return redirect()->route('login');
    });

    Route::post('comment-delete', function () {
        $commentId = request()->input('id');
        App\Comment::destroy($commentId);

        return response()->json(['status' => 'ok']);
    });

    Route::post('comment-update', function () {
        $file = request()->file('image');
        $commentId = request()->input('commentId');
        $commentableId = request()->input('commentableId');
        $commentableType = request()->input('commentableType');
        $message = request()->input('message');

        $comment = App\Comment::findOrFail($commentId);
        $comment->body = $message;
        $comment->save();

        $model = App::make('App\\' . ucfirst($commentableType));
        $commentable = $model::findOrFail($commentableId);
        $commentable->comments()->save($comment);
        $commentable->load('comments.user');

        $view = view('partials.comments', [
            'commentableId' => $commentableId,
            'commentableType' => $commentableType,
            'comments' => App\Comment::getCommentsWithReplies($commentable)
        ])->render();

        return response()->json(['comments' => $view]);
    });

    // Save user comment
    Route::post('comment', function () {
        $file = request()->file('image');
        $parentId = request()->input('parentId');
        $commentableId = request()->input('commentableId');
        $commentableType = request()->input('commentableType');
        $message = request()->input('message');

        $fileName = null;

        if ($file) {
            $image = \Image::make($file);
            $image->orientate();
            $image->resize(800, null, function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            });
            $extension = $file->getClientOriginalExtension();
            $fileName = md5(microtime()) . '.' . $extension;
            $image->save(storage_path('app/public/comments/'. $fileName));
        }

        if ($parentId === 'undefined') {
            $parentId = null;
        }

        $comment = new App\Comment([
            'parent_id' => $parentId,
            'user_id' => auth()->user()->id,
            'organization_id' => auth()->user()->organization_id,
            'body' => $message,
            'file' => $fileName
        ]);

        $model = App::make('App\\' . ucfirst($commentableType));
        $commentable = $model::findOrFail($commentableId);
        $commentable->comments()->save($comment);
        $commentable->load('comments.user');

        $view = view('partials.comments', [
            'commentableId' => $commentableId,
            'commentableType' => $commentableType,
            'comments' => App\Comment::getCommentsWithReplies($commentable)
        ])->render();

        return response()->json(['comments' => $view]);
    });

    // Save user answers
    Route::post('answers', function () {
        $answers = request()->input('answers');

        if ($answers) {
            $answers = json_decode($answers, true);
        }

        $task = App\Task::findOrFail($answers[0]['taskId']);

        $points = $task->type === 'REQUIRED' ? 20 : 10;
        $bonusPoints = 0;

        foreach ($answers as $answer) {
            if ($answer['private'] === true) {
                $file = request()->file($answer['id'] . '_private');
            } else {
                $file = request()->file($answer['id'] . '_public');
            }

            $fileName = null;

            if ($file) {
                $image = \Image::make($file);
                $image->orientate();
                $image->resize(800, null, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                });
                $extension = $file->getClientOriginalExtension();
                $fileName = md5(microtime()) . '.' . $extension;
                $image->save(storage_path('app/public/answers/'. $fileName));
            }

            App\Answer::create([
                'organization_id' => auth()->user()->organization_id,
                'user_id' => auth()->user()->id,
                'task_id' => $answer['taskId'],
                'question_id' => $answer['id'],
                'body' => $answer['body'],
                'private' => $answer['private'] === true,
                'file' => $fileName
            ]);

            if ($answer['private'] !== true) {
                $bonusPoints = 10;
            }
        }

        if ($task->day === 0) {
            $points = 0;
            $bonusPoints = 0;
        }

        $points = $points + $bonusPoints;

        auth()->user()->points += $points;
        auth()->user()->save();

        return response()->json(['status' => 'ok']);
    });

    // User game tasks
    Route::get('tasks', function () {
        $user = auth()->user();

        if ($gameId = request()->get('game_id')) {
            $game = App\Game::findOrFail($gameId);

            if ($game->organization_id === $user->organization_id) {
                $user->game_id = $gameId;
                $user->save();

                return redirect()->to('tasks');
            }
        }

        $user->load('game.tasks');

        $game = $user->game;
        $tasks = $user->game ? $user->game->tasks->filter(function ($value, $key) {
            return !$value->hidden;
        }) : [];

        return view('tasks', compact('game', 'tasks'));
    })->name('tasks');

    // Game task
    Route::get('task/{id}', function ($id) {
        $task = App\Task::with([
            'game',
            'userAnswers.user',
            'userAnswers.comments.user',
            'comments.user'
        ])->findOrFail($id);

        if ($task->hidden || $task->organization_id !== auth()->user()->organization_id) {
            abort(404);
        }

        $otherAnswers = $task->userAnswers
            ->filter(function ($answer, $key) {
                return !$answer->private;
            })
            ->groupBy('user_id');

        $taskStatus = auth()->user()->getTaskStatus($task);

        return view('task', compact('task', 'otherAnswers', 'taskStatus'));
    })->name('task');

    Route::get('results', function (Illuminate\Http\Request $request) {
        $users = [];

        if (auth()->user()->game) {
            $query = App\User::where('organization_id', auth()->user()->game->organization_id)
                ->where('game_id', auth()->user()->game->id);

            if ($sorting = $request->get('sort')) {
                $attribute = explode(':', $sorting)[0];
                $sort = explode(':', $sorting)[1];

                if ($attribute === 'name' && in_array($sort, ['asc', 'desc'])) {
                    $query->orderBy('firstname', $sort);
                }

                if ($attribute === 'points' && in_array($sort, ['asc', 'desc'])) {
                    $query->orderBy('points', $sort);
                }
            } else {
                $query->orderBy('points', 'desc');
            }

            $users = $query->get();

            if ($sorting) {
                if ($attribute === 'team_points' && in_array($sort, ['asc', 'desc'])) {
                    if ($sort == 'asc') {
                        $users = $users->sortBy('team_points');
                    } else {
                        $users = $users->sortByDesc('team_points');
                    }
                }
            }
        }

        return view('results', compact('users'));
    })->name('results');

    Route::get('feed', function () {
        $feeds = App\Feed::with(['user', 'organization', 'comments'])
            ->where('organization_id', auth()->user()->organization_id)
            ->whereNull('type')
            ->orderByDesc('id')
            ->get();

        return view('feed', compact('feeds'));
    })->name('feed');

    Route::get('methods', function () {
        $user = auth()->user();
        $user->load('game.tasks');

        $tasks = $user->game->tasks->filter(function ($value, $key) {
            return $value->method && !$value->hidden;
        });

        return view('methods', compact('tasks'));
    })->name('methods');

    Route::get('method/{method}', function ($method) {
        if (Storage::disk('public')->exists($method)) {
            return Storage::download($method);
        } else {
            abort(404);
        }
    })->name('method');

    Route::get('faq/{faqId?}', function ($faqId = null) {
        $faqs = App\Faq::orderByDesc('id')->get();
        return view('faq', compact('faqs'));
    })->name('faq');

    Route::get('rules', function () {
        $page = App\Page::find(1);
        return view('rules', compact('page'));
    })->name('rules');

    Route::get('help-together', function () {
        $donations = App\Feed::with(['user', 'organization', 'comments'])
            ->where('organization_id', auth()->user()->organization_id)
            ->whereType('DONATIONS')
            ->orderByDesc('id')
            ->get();

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    const TYPES = [
        'REQUIRED' => 'Pamata',
        'ADDITIONAL' => 'Bonus',
        'NOT_REQUIRED' => 'Nav obligāts',
    ];

    /**
     * The attributes that are guarded.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'questions' => 'array',
        'hidden' => 'boolean'
    ];

    /**
     * The "booting" method of the model.
     *
     * @return void
     */
    protected static function boot()
    {
        parent::boot();
    }

    /**
     * Get the task's type.
     *
     * @param  string  $value
     * @return string
     */
    public function getHumanTypeAttribute()
    {
        return self::TYPES[$this->type];
    }

    /**
     * Get the organization that owns the task.
     */
    public function organization()
    {
        return $this->belongsTo('App\Organization');
    }

    /**
     * Get the game that owns the task.
     */
    public function game()
    {
        return $this->belongsTo('App\Game');
    }

    /**
     * Get task answers
     */
    public function answers()
    {
        return $this->hasMany('App\Answer');
    }

    /**
     * Get all of the task's comments.
     */
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    /**
     * Get the user's answers.
     */
    public function userAnswers()
    {
        return $this->hasMany('App\Answer')
            ->where('organization_id', auth()->user()->organization_id);
    }
}

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Laravel\Nova\Nova;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are guarded.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Always eager load these relationships
     *
     * @var array
     */
    protected $with = ['game'];

    /**
     * Bootstrap any model services.
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        // Nova::serving(function () {
            static::saved(function ($user) {
                $prevFriendid = $user->getOriginal('friend_id');

                if ($prevFriendid !== $user->friend_id) {
                    if ($user->friend_id) {
                        $friend = self::findOrFail($user->friend_id);
                        $friend->friend_id = $user->id;
                        $friend->unsetEventDispatcher();
                        $friend->save();
                    } else {
                        $friend = self::findOrFail($prevFriendid);
                        $friend->friend_id = null;
                        $friend->unsetEventDispatcher();
                        $friend->save();
                    }
                }
            });
        // });
    }

    /**
     * Get team rank.
     */
    public function getTeamPointsAttribute()
    {
        if ($this->friend_id) {
            $friend = self::findOrFail($this->friend_id);
            return $friend->points + $this->points;
        }

        return 0;
    }

    /**
     * Get users rank.
     */
    public function getRankAttribute()
    {
        $points = $this->attributes['points'];

        if ($points >= 260) {
            $rank = 7;
        } else if ($points >= 200) {
            $rank = 6;
        } else if ($points >= 150) {
            $rank = 5;
        } else if ($points >= 100) {
            $rank = 4;
        } else if ($points >= 60) {
            $rank = 3;
        } else if ($points >= 30) {
            $rank = 2;
        } else {
            $rank = 1;
        }

        return $rank;
    }

    /**
     * Get users rank name.
     */
    public function getRankNameAttribute()
    {
        $points = $this->attributes['points'];

        if ($points >= 250) {
            $rank = 'Homo Felicitius';
        } else if ($points >= 200) {
            $rank = 'Aizrautīgais Burvis';
        } else if ($points >= 150) {
            $rank = 'Burvis';
        } else if ($points >= 100) {
            $rank = 'Burvju māceklis';
        } else if ($points >= 60) {
            $rank = 'Viedais Rūķis';
        } else if ($points >= 30) {
            $rank = 'Rūķis';
        } else {
            $rank = 'Mazais Rūķis';
        }

        return $rank;
    }

    /**
     * Get the game that the user plays.
     */
    public function getPointsProgressAttribute()
    {
        if ($this->points < 1 || $this->game->max_points < 1) {
            return 0;
        }

        $progress = intval($this->points/$this->game->max_points*100);

        return $progress > 100 ? 100 : $progress;
    }

    /**
     * Get the game that the user plays.
     */
    public function getTeamPointsProgressAttribute()
    {
        if ($this->team_points < 1 || $this->game->max_points_team < 1) {
            return 0;
        }

        $progress = intval($this->team_points/$this->game->max_points_team*100);

        return $progress > 100 ? 100 : $progress;
    }

    /**
     * Get the game that the user plays.
     */
    public function game()
    {
        return $this->belongsTo('App\Game');
    }

    /**
     * Get user organization games.
     */
    public function games()
    {
        return $this->hasMany('App\Game', 'organization_id', 'organization_id');
    }

    /**
     * Get user answer on question.
     */
    public function getAnswer($taskId, $qid, $private = false)
    {
        $answer = $this->hasOne('App\Answer')
            ->where('task_id', $taskId)
            ->where('question_id', $qid)
            ->where('private', $private)
            ->first();

        return $answer;
    }

    /**
     * Has user answered?
     */
    public function getTaskStatus($task)
    {
        if ($task->day === 0) {
            return 'bg-green';
        }

        $answer = $this->hasOne('App\Answer')
            ->where('task_id', $task->id)
            ->first();

        if ($answer) {
            $diff = $answer->created_at->diffInMinutes(Carbon::now());
            return $diff < 5 ? 'bg-orange' : 'bg-green';
        }

        return 'bg-red';
    }

    /**
     * Get the organization that owns the user.
     */
    public function organization()
    {
        return $this->belongsTo('App\Organization');
    }

    /**
     * Get all of the user's comments.
     */
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    /**
     * Get all of the user's answers.
     */
    public function answers()
    {
        return $this->hasMany('App\Answer');
    }

    /**
     * Get all of the user's answers.
     */
    public function getAnswers($taskId)
    {
        return $this->hasOne('App\Answer')->where('task_id', $taskId);
    }
}

resources/views/faq.blade.php
@extends('layouts.main')
@section('title', 'FAQ')
@section('content')
<h1>FAQ</h1>
<div class="wide-bg grey-bg">
    <div class="faq">
        @foreach($faqs as $k => $faq)
            <h3><a href="{{ route('faq', $k) }}">{{ $faq->title }}</a></h3>
            <div>
                {!! $faq->body !!}
            </div>
        @endforeach
    </div>
    <!-- faq -->
</div>
<!-- wide-bg -->
@endsection

resources/views/methods.blade.php
@extends('layouts.main')
@section('title', 'Metodes')
@section('content')
<h1>Metodes</h1>
<div class="wide-bg grey-bg">
    <div class="methods">
        <ul>
            @unless ($tasks->count())
                <li>Neviena metode netika atrasta.</li>
            @endunless
            @foreach($tasks as $task)
                <li><span class="day">{{ $task->day }}<span>diena</span></span>
                    <div>{{ $task->name }} <span>{{ $task->human_type }}</span><a href="{{ route('method', $task->method) }}">Metode</a></div>
                </li>
            @endforeach
        </ul>
    </div>
    <!-- methods -->
</div>
<!-- wide-bg -->
@endsection

resources/views/results.blade.php
@extends('layouts.main')
@section('title', 'Rezultātu tabula')
@section('content')
<h1>Rezultātu tabula</h1>

<div class="wide-bg grey-bg">

    <div class="results">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tbody>
                <tr>
                    <th width="45%">
                        @if(Request::get('sort') === 'name:asc')
                            <a href="{{ route('results', ['sort' => 'name:desc']) }}">Dalībnieka vārds, uzvārds<div class="r-arrows r-arrows-up"></div></a>
                        @else
                            <a href="{{ route('results', ['sort' => 'name:asc']) }}">Dalībnieka vārds, uzvārds<div class="r-arrows r-arrows-down"></div></a>
                        @endif
                    </th>
                    <th>
                        @if(Request::get('sort') === 'points:asc')
                            <a href="{{ route('results', ['sort' => 'points:desc']) }}">Pats<div class="r-arrows r-arrows-up"></div></a>
                        @else
                            <a href="{{ route('results', ['sort' => 'points:asc']) }}">Pats<div class="r-arrows r-arrows-down"></div></a>
                        @endif
                    </th>
                    <th width="100%">
                        @if(Request::get('sort') === 'team_points:asc')
                            <a href="{{ route('results', ['sort' => 'team_points:desc']) }}">Komanda<div class="r-arrows r-arrows-up"></div></a>
                        @else
                            <a href="{{ route('results', ['sort' => 'team_points:asc']) }}">Komanda<div class="r-arrows r-arrows-down"></div></a>
                        @endif
                    </th>
                    <th width="29%">
                        Līmenis
                    </th>
                </tr>
                @foreach($users as $user)
                <tr>
                    <td>
                        <div class="r-img" @if($user->picture) style="background-image:url({{ asset('storage/avatars/'.$user->picture) }})" @endif></div>
                        <a href="{{ route('user', $user->id) }}">{{ $user->firstname }} {{ $user->lastname }}</a></td>
                    <td>{{ $user->points }}</td>
                    <td>{{ $user->team_points }}</td>
                    <td>
                        <div class="character-icon ch-{{ $user->rank }}-h"></div>{{ $user->rank_name }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    <!-- results -->

</div>
<!-- wide-bg -->
@endsection

resources/views/rules.blade.php
@extends('layouts.main')
@section('title', 'Noteikumi')
@section('content')
<h1>Spēles noteikumi</h1>
<div class="wide-bg">
    @if($page)
        {!! $page->body !!}
    @endif
</div>
<!-- wide-bg -->
@endsection

resources/views/task.blade.php
@extends('layouts.main')
@section('title', 'Spēles uzdevums')
@section('content')
    <div class="task-top">
        @if($taskStatus === 'bg-red')
            <div class="status status-r">Uzdevums nav izpildīts</div>
        @elseif($taskStatus === 'bg-orange')
            <div class="status status-o">Uzdevums tiek izskatīts</div>
        @elseif($taskStatus === 'bg-green')
            <div class="status status-g">Uzdevums pieņemts</div>
        @endif
        <a href="{{ route('tasks') }}" class="list">Uzdevumu saraksts<span></span></a>
        <span>{{ $task->game->name }}<span>{{ $task->day }}. diena</span></span>
    </div>

    <h2>{{ $task->name }}</h2>
    <span class="task-info">{{ $task->human_type }} uzdevums</span>

    <div class="task-descr fr-view">
        {!! $task->body !!}
    </div>
    <!-- task-descr -->

    @if($task->method)
        <a href="{{ route('method', $task->method) }}" class="task-method">Uzdevuma metode<span></span></a>
    @endif

    <div class="explanation fr-view">
        <h3>Skaidrojums ko rakstīt uzdevumā</h3>
        {!! $task->description !!}
    </div>
    <!-- explanation -->

    @if($task->questions)
        <div class="answers">
            <h3>Tava atbilde</h3>
            <ul>
                @foreach($task->questions as $k => $q)
                    <?php
                        $uAnswerPrivate = auth()->user()->getAnswer($task->id, $q['id'], true);
                        $uAnswerPublic= auth()->user()->getAnswer($task->id, $q['id']);
                    ?>
                    <li>
                        <h3>{{ $k+1 }}. {{ $q['question'] }}</h3>
                        <div>
                            <textarea data-private="true" data-file="fpriv{{ $q['id'] }}" data-id="{{ $q['id'] }}" placeholder="Atbilde nav publiski redzama">{{ optional($uAnswerPrivate)->body }}</textarea>
                            <div class="attachment" @if(optional($uAnswerPrivate)->file) style="opacity:1;background-image:url(/img/checked.png)" @endif><input class="fpriv{{ $q['id'] }}" type="file" accept="image/*"></div>
                        </div>
                        <div class="not-public">
                            <textarea data-id="{{ $q['id'] }}" data-file="fpub{{ $q['id'] }}" placeholder="Atbilde ir publiski redzama">{{ optional($uAnswerPublic)->body }}</textarea>
                            <div class="attachment" @if(optional($uAnswerPublic)->file) style="opacity:1;background-image:url(/img/checked.png)" @endif><input class="fpub{{ $q['id'] }}" type="file" accept="image/*"></div>
                        </div>
                    </li>
                @endforeach
            </ul>
            @if(auth()->user()->getAnswers($task->id)->count())
                <div class="button sended">Atbilde nosūtīta</div>
            @else
                <button data-task-id="{{ $task->id }}" class="send-form" type="button" disabled="disabled">Nosūtīt atbildi</button>
                <div class="button sended" style="display: none">Atbilde nosūtīta</div>
            @endif
        </div>
        <!-- answers -->
    @endif

    <div class="answers-tabs">
        <ul>
            <li><a href="#other_answers">Citu atbildes<br>šim uzdevumam</a></li>
            <li><a href="#comments">Pajautā trenerim <span>Anonīmam jautājumam, raksti<br>spele@cilvekam.lv</span></a></li>
        </ul>
        <div id="other_answers" class="comments-list">
            <ul>
                @foreach($otherAnswers as $answers)
                    <li>
                        <div class="c-content">
                            <div class="c-img-big" id="c-fimg-big-{{ $answers[0]->id }}">
                                <div>
                                    @if($answers[0]->user->picture)
                                        <img src="{{ asset('storage/avatars/'.$answers[0]->user->picture) }}">
                                    @else
                                        <img src="/img/user.png">
                                    @endif
                                    <a href="{{ route('user', $answers[0]->user->id) }}">
                                        Uzraksti komentāru
                                    </a>
                                </div>
                            </div>
                            <a data-fancybox data-src="#c-fimg-big-{{ $answers[0]->id }}" href="javascript:;" class="c-img" @if($answers[0]->user->picture) style="background-image:url({{ asset('storage/avatars/'.$answers[0]->user->picture) }})" @endif></a>
                            <div class="c-top">
                                <a href="{{ route('user', $answers[0]->user->id) }}">
                                    {{ $answers[0]->user->firstname }} {{ $answers[0]->user->lastname }}
                                </a>
                            </div>
                            <div class="c-text">
                                @foreach($answers as $k => $answer)
                                    <span><p>{{ $k+1 }}. {!! nl2br(e($answer->body)) !!}</p></span>
                                    @if($answer->file)
                                        <div class="c-text-img answer">
                                            <a data-fancybox href="{{ asset('storage/answers/'.$answer->file) }}" data-width="800">
                                                <img src="{{ asset('storage/answers/'.$answer->file) }}">
                                            </a>
                                        </div>
                                    @endif
                                @endforeach
                                {{-- @if(auth()->user()->id === $answers[0]->user->id)
                                    @include('partials.edit_content', ['id' => $answers[0]->id, 'answers' => $answers])
                                @endif --}}
                                <a href="javascript:;" class="morelink">Vairāk</a>
                            </div>
                            {{-- <div class="c-reply">Atbildēt</div> --}}
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>
        <div id="comments">
            <div class="add-comment">
                <form>
                    <textarea name="comment" placeholder="Ieraksti savu komentāru..."></textarea>
                    <div class="emoji">
                        <div class="add-emoji"></div>
                        <div class="emojis">
                            @include('partials.emo')
                        </div>
                    </div>
                    <div class="add-image"><input type="file" name="image"></div>
                    <button data-commentable-type="task" data-commentable-id="{{ $task->id }}" class="add" type="button" disabled="disabled"></button>
                </form>
            </div>
            <div class="comments-list">
                @include('partials.comments', ['commentableId' => $task->id, 'commentableType' => 'task', 'comments' => App\Comment::getCommentsWithReplies($task)])
            </div>
            <!-- comments-list -->
        </div>
    </div>
    <!-- answers-tabs -->
@endsection

resources/views/tasks.blade.php
@extends('layouts.main')
@section('title', 'Spēles uzdevumi')
@section('content')
<div class="wide-bg">
    @if($game)
        <h1>{{ $game->name }}</h1>
    @else
        <h1>Nav izvēlēta neviena spēle</h1>
    @endif

    @if($game)
        <div class="tasks-text">
            {{ $game->description }}
        </div>
    @endif

    <!-- find-text -->

    <div class="tasks-content">
        <div class="tasks">
            @foreach($tasks as $task)
                <div>
                    <a href="{{ route('task', $task->id) }}" class="{{ auth()->user()->getTaskStatus($task) }}">
                        {{ $task->name }}
                        <div>{{ $task->human_type }}</div>
                        <span>
                            @if($task->card_label)
                                {{ $task->card_label }}
                            @else
                                {{ $task->day }}. diena
                            @endif
                        </span>
                    </a>
                </div>
            @endforeach
        </div>
        <!-- tasks -->
    </div>
    <!-- tasks-content -->

    @if($game)
        <div class="task-m">
            <div class="task-r">Uzdevums nav izpildīts</div>
            <div class="task-o">Uzdevums tiek izskatīts</div>
            <div class="task-g">Uzdevums pieņemts</div>
        </div>
    @endif
</div>
<!-- wide-bg -->
@endsection