routes/web.php
<?php

Auth::routes();


Route::get('test', function () {
    // $games = \App\Game::with('tasks')->get();

    // foreach ($games as $game) {
    //     if ($game->starts_at->toDateString() <= today()->toDateString()) {
    //         $lastGamesDay = \App\Task::whereGameId($game->id)->max('day');

    //         if ($game->active_day < $lastGamesDay) {
    //             $game->active_day += 1;
    //             $game->save();

    //             foreach ($game->tasks as $task) {
    //                 if ($game->active_day === $task->day) {
    //                     $task->hidden = false;
    //                     $task->save();
    //                 }
    //             }
    //         }
    //     }
    // }

    dd(true);
});

Route::middleware(['auth'])->group(function () {
    // Logout web user
    Route::get('logout', function () {
        auth('web')->logout();
        return redirect()->route('login');
    });

    Route::post('comment-delete', function () {
        $commentId = request()->input('id');
        App\Comment::destroy($commentId);

        return response()->json(['status' => 'ok']);
    });

    Route::post('comment-update', function () {
        $file = request()->file('image');
        $commentId = request()->input('commentId');
        $commentableId = request()->input('commentableId');
        $commentableType = request()->input('commentableType');
        $message = request()->input('message');

        $comment = App\Comment::findOrFail($commentId);
        $comment->body = $message;
        $comment->save();

        $model = App::make('App\\' . ucfirst($commentableType));
        $commentable = $model::findOrFail($commentableId);
        $commentable->comments()->save($comment);
        $commentable->load('comments.user');

        $view = view('partials.comments', [
            'commentableId' => $commentableId,
            'commentableType' => $commentableType,
            'comments' => App\Comment::getCommentsWithReplies($commentable)
        ])->render();

        return response()->json(['comments' => $view]);
    });

    // Save user comment
    Route::post('comment', function () {
        $file = request()->file('image');
        $parentId = request()->input('parentId');
        $commentableId = request()->input('commentableId');
        $commentableType = request()->input('commentableType');
        $message = request()->input('message');

        $fileName = null;

        if ($file) {
            $image = \Image::make($file);
            $image->orientate();
            $image->resize(800, null, function ($constraint) {
                $constraint->aspectRatio();
                $constraint->upsize();
            });
            $extension = $file->getClientOriginalExtension();
            $fileName = md5(microtime()) . '.' . $extension;
            $image->save(storage_path('app/public/comments/'. $fileName));
        }

        if ($parentId === 'undefined') {
            $parentId = null;
        }

        $comment = new App\Comment([
            'parent_id' => $parentId,
            'user_id' => auth()->user()->id,
            'organization_id' => auth()->user()->organization_id,
            'body' => $message,
            'file' => $fileName
        ]);

        $model = App::make('App\\' . ucfirst($commentableType));
        $commentable = $model::findOrFail($commentableId);
        $commentable->comments()->save($comment);
        $commentable->load('comments.user');

        $view = view('partials.comments', [
            'commentableId' => $commentableId,
            'commentableType' => $commentableType,
            'comments' => App\Comment::getCommentsWithReplies($commentable)
        ])->render();

        return response()->json(['comments' => $view]);
    });

    // Save user answers
    Route::post('answers', function () {
        $answers = request()->input('answers');

        if ($answers) {
            $answers = json_decode($answers, true);
        }

        $task = App\Task::findOrFail($answers[0]['taskId']);

        $points = $task->type === 'REQUIRED' ? 20 : 10;
        $bonusPoints = 0;

        foreach ($answers as $answer) {
            if ($answer['private'] === true) {
                $file = request()->file($answer['id'] . '_private');
            } else {
                $file = request()->file($answer['id'] . '_public');
            }

            $fileName = null;

            if ($file) {
                $image = \Image::make($file);
                $image->orientate();
                $image->resize(800, null, function ($constraint) {
                    $constraint->aspectRatio();
                    $constraint->upsize();
                });
                $extension = $file->getClientOriginalExtension();
                $fileName = md5(microtime()) . '.' . $extension;
                $image->save(storage_path('app/public/answers/'. $fileName));
            }

            App\Answer::create([
                'organization_id' => auth()->user()->organization_id,
                'user_id' => auth()->user()->id,
                'task_id' => $answer['taskId'],
                'question_id' => $answer['id'],
                'body' => $answer['body'],
                'private' => $answer['private'] === true,
                'file' => $fileName
            ]);

            if ($answer['private'] !== true) {
                $bonusPoints = 10;
            }
        }

        if ($task->day === 0) {
            $points = 0;
            $bonusPoints = 0;
        }

        $points = $points + $bonusPoints;

        auth()->user()->points += $points;
        auth()->user()->save();

        return response()->json(['status' => 'ok']);
    });

    // User game tasks
    Route::get('tasks', function () {
        $user = auth()->user();

        if ($gameId = request()->get('game_id')) {
            $game = App\Game::findOrFail($gameId);

            if ($game->organization_id === $user->organization_id) {
                $user->game_id = $gameId;
                $user->save();

                return redirect()->to('tasks');
            }
        }

        $user->load('game.tasks');

        $game = $user->game;
        $tasks = $user->game ? $user->game->tasks->filter(function ($value, $key) {
            return !$value->hidden;
        }) : [];

        return view('tasks', compact('game', 'tasks'));
    })->name('tasks');

    // Game task
    Route::get('task/{id}', function ($id) {
        $task = App\Task::with([
            'game',
            'userAnswers.user',
            'userAnswers.comments.user',
            'comments.user'
        ])->findOrFail($id);

        if ($task->hidden || $task->organization_id !== auth()->user()->organization_id) {
            abort(404);
        }

        $otherAnswers = $task->userAnswers
            ->filter(function ($answer, $key) {
                return !$answer->private;
            })
            ->groupBy('user_id');

        $taskStatus = auth()->user()->getTaskStatus($task);

        return view('task', compact('task', 'otherAnswers', 'taskStatus'));
    })->name('task');

    Route::get('results', function (Illuminate\Http\Request $request) {
        $users = [];

        if (auth()->user()->game) {
            $query = App\User::where('organization_id', auth()->user()->game->organization_id)
                ->where('game_id', auth()->user()->game->id);

            if ($sorting = $request->get('sort')) {
                $attribute = explode(':', $sorting)[0];
                $sort = explode(':', $sorting)[1];

                if ($attribute === 'name' && in_array($sort, ['asc', 'desc'])) {
                    $query->orderBy('firstname', $sort);
                }

                if ($attribute === 'points' && in_array($sort, ['asc', 'desc'])) {
                    $query->orderBy('points', $sort);
                }
            } else {
                $query->orderBy('points', 'desc');
            }

            $users = $query->get();

            if ($sorting) {
                if ($attribute === 'team_points' && in_array($sort, ['asc', 'desc'])) {
                    if ($sort == 'asc') {
                        $users = $users->sortBy('team_points');
                    } else {
                        $users = $users->sortByDesc('team_points');
                    }
                }
            }
        }

        return view('results', compact('users'));
    })->name('results');

    Route::get('feed', function () {
        $feeds = App\Feed::with(['user', 'organization', 'comments'])
            ->where('organization_id', auth()->user()->organization_id)
            ->whereNull('type')
            ->orderByDesc('id')
            ->get();

        return view('feed', compact('feeds'));
    })->name('feed');

    Route::get('methods', function () {
        $user = auth()->user();
        $user->load('game.tasks');

        $tasks = $user->game->tasks->filter(function ($value, $key) {
            return $value->method && !$value->hidden;
        });

        return view('methods', compact('tasks'));
    })->name('methods');

    Route::get('method/{method}', function ($method) {
        if (Storage::disk('public')->exists($method)) {
            return Storage::download($method);
        } else {
            abort(404);
        }
    })->name('method');

    Route::get('faq/{faqId?}', function ($faqId = null) {
        $faqs = App\Faq::orderByDesc('id')->get();
        return view('faq', compact('faqs'));
    })->name('faq');

    Route::get('rules', function () {
        $page = App\Page::find(1);
        return view('rules', compact('page'));
    })->name('rules');

    Route::get('help-together', function () {
        $donations = App\Feed::with(['user', 'organization', 'comments'])
            ->where('organization_id', auth()->user()->organization_id)
            ->whereType('DONATIONS')
            ->orderByDesc('id')
            ->get();

app/User.php
<?php

namespace App;

use Carbon\Carbon;
use Laravel\Nova\Nova;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are guarded.
     *
     * @var array
     */
    protected $guarded = ['id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Always eager load these relationships
     *
     * @var array
     */
    protected $with = ['game'];

    /**
     * Bootstrap any model services.
     *
     * @return void
     */
    public static function boot()
    {
        parent::boot();

        // Nova::serving(function () {
            static::saved(function ($user) {
                $prevFriendid = $user->getOriginal('friend_id');

                if ($prevFriendid !== $user->friend_id) {
                    if ($user->friend_id) {
                        $friend = self::findOrFail($user->friend_id);
                        $friend->friend_id = $user->id;
                        $friend->unsetEventDispatcher();
                        $friend->save();
                    } else {
                        $friend = self::findOrFail($prevFriendid);
                        $friend->friend_id = null;
                        $friend->unsetEventDispatcher();
                        $friend->save();
                    }
                }
            });
        // });
    }

    /**
     * Get team rank.
     */
    public function getTeamPointsAttribute()
    {
        if ($this->friend_id) {
            $friend = self::findOrFail($this->friend_id);
            return $friend->points + $this->points;
        }

        return 0;
    }

    /**
     * Get users rank.
     */
    public function getRankAttribute()
    {
        $points = $this->attributes['points'];

        if ($points >= 260) {
            $rank = 7;
        } else if ($points >= 200) {
            $rank = 6;
        } else if ($points >= 150) {
            $rank = 5;
        } else if ($points >= 100) {
            $rank = 4;
        } else if ($points >= 60) {
            $rank = 3;
        } else if ($points >= 30) {
            $rank = 2;
        } else {
            $rank = 1;
        }

        return $rank;
    }

    /**
     * Get users rank name.
     */
    public function getRankNameAttribute()
    {
        $points = $this->attributes['points'];

        if ($points >= 250) {
            $rank = 'Homo Felicitius';
        } else if ($points >= 200) {
            $rank = 'Aizrautīgais Burvis';
        } else if ($points >= 150) {
            $rank = 'Burvis';
        } else if ($points >= 100) {
            $rank = 'Burvju māceklis';
        } else if ($points >= 60) {
            $rank = 'Viedais Rūķis';
        } else if ($points >= 30) {
            $rank = 'Rūķis';
        } else {
            $rank = 'Mazais Rūķis';
        }

        return $rank;
    }

    /**
     * Get the game that the user plays.
     */
    public function getPointsProgressAttribute()
    {
        if ($this->points < 1 || $this->game->max_points < 1) {
            return 0;
        }

        $progress = intval($this->points/$this->game->max_points*100);

        return $progress > 100 ? 100 : $progress;
    }

    /**
     * Get the game that the user plays.
     */
    public function getTeamPointsProgressAttribute()
    {
        if ($this->team_points < 1 || $this->game->max_points_team < 1) {
            return 0;
        }

        $progress = intval($this->team_points/$this->game->max_points_team*100);

        return $progress > 100 ? 100 : $progress;
    }

    /**
     * Get the game that the user plays.
     */
    public function game()
    {
        return $this->belongsTo('App\Game');
    }

    /**
     * Get user organization games.
     */
    public function games()
    {
        return $this->hasMany('App\Game', 'organization_id', 'organization_id');
    }

    /**
     * Get user answer on question.
     */
    public function getAnswer($taskId, $qid, $private = false)
    {
        $answer = $this->hasOne('App\Answer')
            ->where('task_id', $taskId)
            ->where('question_id', $qid)
            ->where('private', $private)
            ->first();

        return $answer;
    }

    /**
     * Has user answered?
     */
    public function getTaskStatus($task)
    {
        if ($task->day === 0) {
            return 'bg-green';
        }

        $answer = $this->hasOne('App\Answer')
            ->where('task_id', $task->id)
            ->first();

        if ($answer) {
            $diff = $answer->created_at->diffInMinutes(Carbon::now());
            return $diff < 5 ? 'bg-orange' : 'bg-green';
        }

        return 'bg-red';
    }

    /**
     * Get the organization that owns the user.
     */
    public function organization()
    {
        return $this->belongsTo('App\Organization');
    }

    /**
     * Get all of the user's comments.
     */
    public function comments()
    {
        return $this->morphMany('App\Comment', 'commentable');
    }

    /**
     * Get all of the user's answers.
     */
    public function answers()
    {
        return $this->hasMany('App\Answer');
    }

    /**
     * Get all of the user's answers.
     */
    public function getAnswers($taskId)
    {
        return $this->hasOne('App\Answer')->where('task_id', $taskId);
    }
}

resources/views/partials/comment.blade.php
<div class="c-content @if($comment->user->admin) -c-highlighted @endif">
    <div class="c-img-big" id="c-img-big-{{ $comment->id }}">
        <div>
             @if($comment->user->picture)
                <img src="{{ asset('storage/avatars/'.$comment->user->picture) }}">
            @else
                <img src="/img/user.png">
            @endif
            <a href="{{ route('user', $comment->user->id) }}">Uzraksti komentāru</a>
        </div>
    </div>
    <a data-fancybox data-src="#c-img-big-{{ $comment->id }}" href="javascript:;" class="c-img" @if($comment->user->picture) style="background-image:url({{ asset('storage/avatars/'.$comment->user->picture) }})" @endif></a>
    <div class="c-top">
        <a href="{{ route('user', $comment->user->id) }}">{{ $comment->user->firstname }} {{ $comment->user->lastname }}</a>
        <span>{{ $comment->created_at->format('d.m.Y H.i') }}</span>
    </div>
    <div class="c-text">
        <div class="c-text-container">
            <span class="c-text-body">{!! nl2br($comment->body) !!}</span>
            {{-- <span class="c-text-body">{!! nl2br(e($comment->body)) !!}</span> --}}
            @if($comment->file)
                <div class="c-text-img">
                    <a data-fancybox href="{{ asset('storage/comments/'.$comment->file) }}" data-width="800">
                        <img src="{{ asset('storage/comments/'.$comment->file) }}">
                    </a>
                </div>
            @endif
        </div>
        @if(auth()->user()->id === $comment->user_id)
            @include('partials.comment_edit', ['id' => $comment->id, 'commentable_id' => $comment->commentable_id, 'commentable_type' =>  'task', 'comment' => $comment])
        @endif
        @if(!$comment->parent_id)
            <div class="c-reply">Atbildēt</div>
        @endif
        <a href="javascript:;" class="morelink">Vairāk</a>
    </div>
    <div class="add-comment">
        <form>
            <textarea name="comment" placeholder="Ieraksti savu komentāru..."></textarea>
            <div class="emoji">
                <div class="add-emoji"></div>
                <div class="emojis">
                    @include('partials.emo')
                </div>
            </div>
            <div class="add-image"><input type="file" accept="image/*" /></div>
            <button data-parent-id="{{ $comment->id }}" data-commentable-id="{{ $commentableId }}" data-commentable-type="{{ $commentableType }}" type="button" class="add"></button>
        </form>
    </div>
</div>

resources/views/partials/comment_edit.blade.php
<div class="c-edit-content">
    <div class="c-edit-bttn"><span></span></div>
    <div class="c-edit-box">
        <a data-fancybox="c-edit" data-src="#c-edit-{{ $id }}" href="javascript:;">Labot</a>
        <a href="javascript:;" data-comment-id="{{ $comment->id }}" class="delete-comment">Dzēst</a>
    </div>
    <div class="c-edit" id="c-edit-{{ $id }}">
    <div>
    <div class="comment-update-form">
        <h4>Labot ierakstu<span data-fancybox-close></span></h4>
        <form class="c-edit-form">
            <div class="c-edit-text">
                {{-- <div class="c-img"></div> --}}
                <textarea>{!! nl2br($comment->body) !!}</textarea>
                <div class="emoji">
                <div class="add-emoji"></div>
                <div class="emojis">
                    @include('partials.emo')
                </div>
                </div>
            </div>
            <ul>
            <li @if(!$comment->file) style="display:none" @endif><div style="background:url({{ asset('storage/comments/'.$comment->file) }})"></div><span></span></li>
            <input  @if($comment->file) style="display:none" @endif type="file" accept="image/*" />
            {{-- <li><div><input type="file" name="myfile" /></div></li>
            <li><div><input type="file" name="myfile" /></div></li>
            <li><div><input type="file" name="myfile" /></div></li> --}}
            </ul>
            <button data-comment-id="{{ $id }}"  data-commentable-id="{{ $commentableId }}" data-commentable-type="{{ $commentableType }}" type="button" class="update-comment">Saglabāt</button>
        </form>
    </div>
    </div>
    </div>
</div>

resources/views/partials/comments.blade.php
<ul>
    @foreach($comments as $comment)
        <li>
            @include('partials.comment', ['commentableId' => $commentableId, 'commentableType' => $commentableType, 'comment' => $comment])
            <ul>
                @foreach($comment->children as $children)
                    <li>
                        @include('partials.comment', ['commentableId' => $commentableId, 'commentableType' => $commentableType, 'comment' => $children])
                    </li>
                @endforeach
            </ul>
        </li>
    @endforeach
</ul>

resources/views/partials/cookies.blade.php
<div class="cookies-container">
    <div>
        <div class="close-cookies"></div>
        <div class="cookies">Šī vietne izmanto sīkdatnes, lai uzlabotu lietošanas pieredzi un optimizētu tās darbību. Turpinot lietot šo vietni,
            jūs piekrītat <a data-fancybox data-src="#cookies" href="javascript:;">sīkdatņu lietošanas noteikumiem</a>!
        </div>
    </div>
</div>

resources/views/partials/emo.blade.php
<img src="/img/emoji/happy.svg" data-emoji=":)" alt="happy">
<img src="/img/emoji/happy2.svg" data-emoji=":D" alt="happy2">
<img src="/img/emoji/confused.svg" data-emoji=":|" alt="confused">
<img src="/img/emoji/thinking.svg" data-emoji=";/" alt="thinking">
<img src="/img/emoji/favorite.svg" data-emoji="8)" alt="favorite">
<img src="/img/emoji/sad.svg" data-emoji=":(" alt="sad">

resources/views/partials/header.blade.php
<div class="header">
    <a href="#" class="logo-mob"></a>
    <div id="menu-bttn">
        <div class="m-line-1"></div>
        <div class="m-line-2"></div>
        <div class="m-line-3"></div>
    </div>
    <div class="find">
        <div>
            <a href="/" class="logo"></a>
            @if(auth()->user()->game)
                <a href="{{ route('tasks') }}">
                    {{ auth()->user()->game->name }}
                </a>
            @endif
        </div>
    </div>
    <div class="top-content">
        <div class="character">
            <div>
                <div class="character-icon ch-{{ auth()->user()->rank }}-h"></div>
                <span>Tu jau esi</span>
                <div class="character-title">{{ auth()->user()->rank_name }}</div>
                <div class="ul-slide-bttn"></div>
            </div>
        </div>
        @if(auth()->user()->game)
            <div class="top-blocks">
                <ul>
                    <li class="your-points">
                        <div>
                            <span class="block-title">Tavi punkti</span>
                            <span class="points"><strong>{{ auth()->user()->points }}</strong> <span>no {{ auth()->user()->game->max_points }}</span></span>
                            <div class="progress-bar">
                                <div style="width: {{ auth()->user()->points_progress }}%"><span>{{ auth()->user()->points_progress }}%</span></div>
                            </div>
                        </div>
                    </li>
                    @if(auth()->user()->game && !auth()->user()->game->team_points_is_hidden)
                        <li class="team-points">
                            <div>
                                <span class="block-title">Komandas punkti</span>
                                <span class="points"><strong>{{ auth()->user()->team_points }}</strong> <span>no {{ auth()->user()->game->max_points_team }}</span></span>
                                <div class="progress-bar">
                                    <div style="width: {{ auth()->user()->team_points_progress }}%"><span>{{ auth()->user()->team_points_progress }}%</span></div>
                                </div>
                            </div>
                        </li>
                    @endif
                    @if(auth()->user()->game && !auth()->user()->game->donation_is_hidden)
                        <li class="donate">
                            <div>
                                <span class="block-title">Palīdzam kopā</span>
                                {{-- <span class="block-text">foršai lauku skolai Latgalē nepieciešami <strong>0 eiro</strong></span> --}}
                                <span class="block-text">Ja savācam kopā 10 000 punktus, veltam @if(auth()->user()->game->id === 9) 150 @else 100 @endif  Eiro...</span>
                                <div class="progress-bar">
                                    <div style="width: {{ auth()->user()->game->getDonationProgress() }}%"><span>{{ auth()->user()->game->getUserTotalPoints() }} punkti</span></div>
                                </div>
                            </div>
                        </li>
                    @endif
                </ul>
            </div>
        @endif
        <!-- top-blocks -->
    </div>
    <!-- top-content -->
</div>
<!-- header -->

resources/views/partials/nav.blade.php
<div class="menu">
    <div class="profile-block">
        <div class="profile-icon" @if(auth()->user()->picture) style="background-image: url({{ asset('storage/avatars/'.auth()->user()->picture) }})" @endif></div>
        {{-- <div class="profile-icon"><a href="mans_profils.html#comments">4</a></div> --}}
        <div class="name">{{ Auth::user()->firstname }} {{ Auth::user()->lastname }}</div>
        <a href="{{ route('logout') }}" class="logout">Iziet</a>
    </div>
    <!-- profile-block -->
    <div class="nav">
        <ul>
            <li><a href="/" class="{{ Route::currentRouteName() === 'home' ? 'current' : '' }}">Mans profils</a></li>
            <li><a href="/tasks" class="{{ in_array(Route::currentRouteName(), ['tasks', 'task']) ? 'current' : '' }}">Spēles uzdevumi</a></li>
            <li><a href="/feed" class="{{ Route::currentRouteName() === 'feed' ? 'current' : '' }}">Čalotava</a></li>
            <li><a href="/results" class="{{ Route::currentRouteName() === 'results' ? 'current' : '' }}">Rezultātu tabula</a></li>
            <li><a href="/methods" class="{{ Route::currentRouteName() === 'methods' ? 'current' : '' }}">Metodes</a></li>
            <li><a href="/faq" class="{{ Route::currentRouteName() === 'faq' ? 'current' : '' }}">FAQ</a></li>
            <li><a href="/rules" class="{{ Route::currentRouteName() === 'rules' ? 'current' : '' }}">Spēles noteikumi</a></li>
            @if(auth()->user()->game && !auth()->user()->game->donation_is_hidden)
                <li><a href="/help-together" class="{{ Route::currentRouteName() === 'help-together' ? 'current' : '' }}">Palīdzam kopā</a></li>
            @endif
            <li><a href="http://cilvekam.lv/" target="_blank" class="cilvekam">Cilvēkam.lv</a></li>
        </ul>
    </div>
</div>
<!-- menu -->